var fs = require("fs");
var path = require("path");
var kleur = require("kleur");
var readline = require("readline");

const STARTER_SCHEMA = {
  schemaVersion: "0.1.0",
  root: {
    type: "Container",
    props: {
      ariaLabel: "My UISchema app"
    },
    children: [
      {
        type: "Card",
        props: {
          ariaLabel: "Welcome card"
        },
        children: [
          {
            type: "Text",
            props: {
              text: "Welcome to UISchema",
              level: "h2"
            }
          },
          {
            type: "Text",
            props: {
              text: "Edit uischema.json and run 'uischema preview' to see your UI.",
              level: "body"
            }
          },
          {
            type: "Button",
            props: {
              text: "Get Started",
              ariaLabel: "Get started button",
              variant: "primary"
            },
            events: {
              onClick: {
                type: "action",
                name: "getStarted"
              }
            }
          }
        ]
      }
    ]
  },
  meta: {
    name: "My UISchema App",
    description: "Generated by @uischema/cli"
  }
};

function ask(rl: ReturnType<typeof readline.createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => rl.question(question, resolve));
}

async function initCommand(args: string[]): Promise<void> {
  console.log(`\n  ${kleur.bold().cyan("UISchema")} — project initializer\n`);

  const nameArg = args[0];

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  let projectName: string;
  if (nameArg) {
    projectName = nameArg;
    console.log(`  ${kleur.gray("Project name:")} ${kleur.white(projectName)}`);
  } else {
    const answer = await ask(rl, `  ${kleur.bold("Project name")} ${kleur.gray("(my-uischema-app)")} › `);
    projectName = answer.trim() || "my-uischema-app";
  }

  rl.close();

  const targetDir = path.resolve(process.cwd(), projectName);

  if (fs.existsSync(targetDir)) {
    console.error(`\n  ${kleur.red("✖")}  Directory already exists: ${kleur.gray(targetDir)}\n`);
    process.exit(1);
  }

  console.log("");
  console.log(`  ${kleur.gray("Creating")} ${kleur.white(projectName)}${kleur.gray("...")}\n`);

  // Create directory structure
  fs.mkdirSync(targetDir, { recursive: true });

  // Write uischema.json
  fs.writeFileSync(
    path.join(targetDir, "uischema.json"),
    JSON.stringify(STARTER_SCHEMA, null, 2) + "\n"
  );
  console.log(`  ${kleur.green("✔")}  Created ${kleur.gray("uischema.json")}`);

  // Write package.json
  const pkg = {
    name: projectName,
    version: "0.0.1",
    private: true,
    dependencies: {
      "@uischema/core": "^0.1.0",
      "@uischema/react": "^0.1.0",
      react: "^18.3.1",
      "react-dom": "^18.3.1"
    },
    devDependencies: {
      "@uischema/cli": "^0.1.0",
      typescript: "^5.6.3"
    },
    scripts: {
      preview: "uischema preview",
      validate: "uischema validate uischema.json"
    }
  };
  fs.writeFileSync(path.join(targetDir, "package.json"), JSON.stringify(pkg, null, 2) + "\n");
  console.log(`  ${kleur.green("✔")}  Created ${kleur.gray("package.json")}`);

  // Write .env.example
  const envExample = [
    "# Required for AI-powered generation",
    "OPENAI_API_KEY=sk-...",
    "# OR",
    "ANTHROPIC_API_KEY=sk-ant-...",
    ""
  ].join("\n");
  fs.writeFileSync(path.join(targetDir, ".env.example"), envExample);
  console.log(`  ${kleur.green("✔")}  Created ${kleur.gray(".env.example")}`);

  // Write .gitignore
  const gitignore = ["node_modules/", ".env", "dist/", "*.tsbuildinfo", ""].join("\n");
  fs.writeFileSync(path.join(targetDir, ".gitignore"), gitignore);
  console.log(`  ${kleur.green("✔")}  Created ${kleur.gray(".gitignore")}`);

  // Write README
  const readme = [
    `# ${projectName}`,
    "",
    "A UISchema project.",
    "",
    "## Getting Started",
    "",
    "```bash",
    "npm install",
    "npm run preview",
    "```",
    "",
    "## Validate",
    "",
    "```bash",
    "npm run validate",
    "```",
    "",
    "## Generate with AI",
    "",
    "```bash",
    "# Add your API key to .env first",
    `uischema generate "a login form with email and password"`,
    "```",
    "",
    "Built with [UISchema](https://github.com/skeehn/ui-schema).",
    ""
  ].join("\n");
  fs.writeFileSync(path.join(targetDir, "README.md"), readme);
  console.log(`  ${kleur.green("✔")}  Created ${kleur.gray("README.md")}`);

  console.log(`\n  ${kleur.bold().green("Done!")} Your project is ready.\n`);
  console.log(`  ${kleur.gray("Next steps:")}`);
  console.log(`    ${kleur.cyan("cd")} ${projectName}`);
  console.log(`    ${kleur.cyan("npm install")}`);
  console.log(`    ${kleur.cyan("npx uischema preview")}\n`);
}

module.exports = { initCommand };
